name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '.github/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  pullrequest:
    permissions:
      contents: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ${{ github.repository }}/.github/workflows/release.yml@main
