name: Produce pandoc export

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BOOK_FILE_NAME: ${{ env.BOOK_FILE_NAME }}.epub
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Write epub
        uses: docker://pandoc/core:2.9
        with:
          args: "-o ${{ env.BOOK_FILE_NAME }}book/00-*.md 01-*.md"

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './version_file.json'

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: |
            ${{ BOOK_FILE_NAME }}

