name: Release epub

on:
  workflow_dispatch:
  workflow_call:

env:
  BOOK_NAME: book-name

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch files in workspace
        id: book-files
        run: echo BOOK_FILES=$(ls book/00-*.md book/01-*.md book/02-*.md) >> $GITHUB_OUTPUT

      - name: Write epub
        uses: docker://pandoc/core:2.14
        with:
          args: "-o ${{ env.BOOK_NAME }}.epub --resource-path=.:book ${{ steps.book-files.outputs.BOOK_FILES }} --standalone"

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './version_file.json'

      - name: Publish release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.tag }}
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: |
            ${{ env.BOOK_NAME }}.epub
